### PR TITLE
Save/load state in xml serializer

### PR DESCRIPTION
**Pull request by Ragzouken**
Closes https://github.com/IRL2/nanover-protocol/issues/283#issuecomment-2450206980

### CODE REVIEW

**Comment by Ragzouken** [comment]
```
<State openmmVersion="8.1.1" stepCount="0" time="0" type="State" version="1">




        <PeriodicBoxVectors>




                <A x="15" y="0" z="0"/>




                <B x="0" y="15" z="0"/>




                <C x="0" y="0" z="15"/>




        </PeriodicBoxVectors>




        <Parameters/>




        <Positions>




                <Position x="0" y="0" z="0"/>




                <Position x="5.288000106811523" y="1.6100000143051147" z="9.359000205993652"/>




                <Position x="2.0510001182556152" y="8.239999771118164" z="-6.785999774932861"/>




                <Position x="-10.6850004196167" y="-.5370000004768372" z="1.9210000038146973"/>




                <Position x="0" y="0" z="5"/>




                <Position x="5.288000106811523" y="1.6100000143051147" z="14.359000205993652"/>




                <Position x="2.0510001182556152" y="8.239999771118164" z="-1.7860000133514404"/>




                <Position x="-10.6850004196167" y="-.5370000004768372" z="6.921000003814697"/>




        </Positions>




        <Velocities>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




                <Velocity x="0" y="0" z="0"/>




        </Velocities>




        <IntegratorParameters/>




</State>

```

**Comment by hjstroud** [comment]
A sensible test system to check that everything works as expected would be the single atom system using the velocity Verlet integrator with some force applied:

1. Run for _n_ steps with some defined force and record the velocity
2. Save the simulation with `save_state=True` to a file
3. Load the simulation from the saved file
4. Assert that the velocity in the loaded simulation equals that of the simulation before saving

It would be worth seeing if saving the state in this way also saves any forces being applied to the system...

**Comment by hjstroud** [comment]
> A sensible test system to check that everything works as expected would be the single atom system using the velocity Verlet integrator with some force applied:
> 
> 1. Run for _n_ steps with some defined force and record the velocity
> 2. Save the simulation with `save_state=True` to a file
> 3. Load the simulation from the saved file
> 4. Assert that the velocity in the loaded simulation equals that of the simulation before saving
> 
> It would be worth seeing if saving the state in this way also saves any forces being applied to the system...

I have added a test that essentially implements this, but for a system of two methane molecules rather than a single atom system, includes multiple forces of different types instead of a single force, and uses a Langevin integrator rather than a Verlet integrator. This test does not test whether any forces applied to the system are also saved. 

I have also added the "save_state=True" flag to the existing tests for serializing/deserializing simulations, to assert that they still work correctly when this flag is set to True.

IMPORTANT NOTE: when writing this test, it was apparent that the velocities loaded from the serialized state were similar but not identical to those of the original state, hence the use of `pytest.approx`. However, it seemed that iterating the serializing/deserializing procedure on the loaded simulation _did_ produce identical values. @Ragzouken I don't think this is something that is related to what NanoVer is doing, it seems more likely to be an OpenMM thing, am I missing anything here?

**Review by Ragzouken — COMMENTED** [review]
Tests look sensible!

**Pull request merged**
