### PR TITLE
Calculate work done by user for OpenMM simulations

### PR DESCRIPTION
**Pull request by hjstroud**
This PR adds the ability to calculate the work done by the user on the molecular system simulated using OpenMM. At the moment this is automatically (i.e. non-optionally) calculated and added to the FrameData.

### CODE REVIEW

**Review by Ragzouken — APPROVED** [review]
Test notwithstanding, all looks good!

**Comment by Ragzouken** [comment]
It doesn't make a lot of sense, but I think for pytest fixtures to work you need to import `single_atom_simulation` into `test_all.py` too

**Comment by hjstroud** [comment]
Tests have now been written to check that the work done is calculated as expected. If the CI passes, do I have the go-ahead to merge @Ragzouken ?

**Comment by Ragzouken** [comment]
> Tests have now been written to check that the work done is calculated as expected. If the CI passes, do I have the go-ahead to merge @Ragzouken ?

Absolutely!

**Pull request merged**
